### ISSUE TITLE
请问微信小程序如何解决适配问题？

### ISSUE THREAD

**Issue by OumCc** [mobikeFE/mobikeFE.github.io#1]
非常感谢你们关于小程序的技术分享。

在此特意想请教小程序是如何做**适配**的？

现在我了解到的是小程序支持 `rem` 还有一个小程序特有的 `rpx` ，不知道你们使用的是怎样的方案？

另外，如何设定 `rem` 的根值也是一个头疼的问题，=_=

**Comment by binnng** [comment]
请使用微信推荐的rpx~

**Comment by OumCc** [comment]
感谢你的回答。

是的，用的是rpx，参考：[让小程序能够适配不同系统平台，微信是这样做的](http://www.ithome.com/html/it/279310.htm)

现在我的做法是：
- 页面上的所有尺寸用的都是 `rpx`
- 字体用 `px` （测试了一下，好像字体用px就可以自适应，在不同屏幕下有一定的**缩放**）
